insert into public.students (full_name, search_name, email, study_year, series, group_code)
values
('Alexandru C. Theodor George', 'alexandru c theodor george', null, '1', '', '1'),
('Anton D.M. Mihai-Cosmin', 'anton d m mihai cosmin', null, '1', '', '1'),
('Armă V.G. Albert-Alexandru', 'arma v g albert alexandru', null, '1', '', '1'),
('Băjenaru A.D Bogdan-Valentin', 'bajenaru a d bogdan valentin', null, '1', '', '1'),
('Bratu V. Cristian-Mădălin', 'bratu v cristian madalin', null, '1', '', '1'),
('Caiuteanu V. Alexandru', 'caiuteanu v alexandru', null, '1', '', '1'),
('Caiuteanu V. Sebastian', 'caiuteanu v sebastian', null, '1', '', '1'),
('Cicu A.F. David-Alberto', 'cicu a f david alberto', null, '1', '', '1'),
('Coculescu C. Teodor', 'coculescu c teodor', null, '1', '', '1'),
('Dascălu I.M. Carmen-Nicoleta', 'dascalu i m carmen nicoleta', null, '1', '', '1'),
('Dănălache E. Ștefan', 'danalache e stefan', null, '1', '', '1'),
('Drăgan I. Mihai-Gabriel', 'dragan i mihai gabriel', null, '1', '', '1'),
('Enciu S. Antonio-Petru', 'enciu s antonio petru', null, '1', '', '1'),
('Florea M.C. Mirel-Mario', 'florea m c mirel mario', null, '1', '', '1'),
('Grigore F.M. Anastasia-Elena', 'grigore f m anastasia elena', null, '1', '', '1'),
('Ionescu D. Luca-Radu', 'ionescu d luca radu', null, '1', '', '1'),
('Manolescu M Robert Daniel Antonio', 'manolescu m robert daniel antonio', null, '1', '', '1'),
('Mihăilă D. Robert Andrei', 'mihaila d robert andrei', null, '1', '', '1'),
('Minescu B. Ștefan-Bogdan', 'minescu b stefan bogdan', null, '1', '', '1'),
('Mitescu (căs. Tănase) G. Naomi', 'mitescu cas tanase g naomi', null, '1', '', '1'),
('Moţoc C.D. Luca-Andrei', 'motoc c d luca andrei', null, '1', '', '1'),
('Nae G. George-Fabrițio', 'nae g george fabritio', null, '1', '', '1'),
('Nicolae P. Marina', 'nicolae p marina', null, '1', '', '1'),
('Pîrvu C. Rareș-Andrei', 'pirvu c rares andrei', null, '1', '', '1'),
('Radu I.L. Ștefan-Valentin', 'radu i l stefan valentin', null, '1', '', '1'),
('Roșu L.Ș. Remus-Alexandru', 'rosu l s remus alexandru', null, '1', '', '1'),
('Spiridon V.I. Răzvan-Alexandru', 'spiridon v i razvan alexandru', null, '1', '', '1'),
('Stoica M.N. Ionuț-Mihai', 'stoica m n ionut mihai', null, '1', '', '1'),
('Ursache I. Cristian-Ionuț', 'ursache i cristian ionut', null, '1', '', '1'),
('Voicu G.M. Andrei', 'voicu g m andrei', null, '1', '', '1'),
('Albănaș M.C. Brandon', 'albanas m c brandon', null, '1', '', '2'),
('Calapod M. Ștefan-Adrian', 'calapod m stefan adrian', null, '1', '', '2'),
('Cană I. Radu-Ștefan', 'cana i radu stefan', null, '1', '', '2'),
('Ciurtin G. Marian-Cristian', 'ciurtin g marian cristian', null, '1', '', '2'),
('Coman C. Andrei-Rareș', 'coman c andrei rares', null, '1', '', '2'),
('Danciu D. Rareș-Ștefan', 'danciu d rares stefan', null, '1', '', '2'),
('Diaconescu L.F. Adrian-Matei', 'diaconescu l f adrian matei', null, '1', '', '2'),
('Dobre M. Costin-Ștefan', 'dobre m costin stefan', null, '1', '', '2'),
('Dochia - Mihai Alexandru', 'dochia mihai alexandru', null, '1', '', '2'),
('Dudeanu G.C. Alexandru', 'dudeanu g c alexandru', null, '1', '', '2'),
('Elisei M. Vladislav', 'elisei m vladislav', null, '1', '', '2'),
('Ene A. Rareș', 'ene a rares', null, '1', '', '2'),
('Frățilă D. Maria-Iuliana', 'fratila d maria iuliana', null, '1', '', '2'),
('Georgescu A.M. Andrei-Radu', 'georgescu a m andrei radu', null, '1', '', '2'),
('Giurcă N.V. Maria-Alexandra', 'giurca n v maria alexandra', null, '1', '', '2'),
('Ion C. Andrei-Auraș', 'ion c andrei auras', null, '1', '', '2'),
('Manciuc M.V. Alexandru-Claudiu', 'manciuc m v alexandru claudiu', null, '1', '', '2'),
('Micu C. Vlad-Alexandru', 'micu c vlad alexandru', null, '1', '', '2'),
('Mirea V.S. Alexandru-Ștefan', 'mirea v s alexandru stefan', null, '1', '', '2'),
('Năsoi M. Adelina-Maria', 'nasoi m adelina maria', null, '1', '', '2'),
('Pahonțu D.A. Rareș Mihai', 'pahontu d a rares mihai', null, '1', '', '2'),
('Pârâianu C. Alecsandra-Elena', 'paraianu c alecsandra elena', null, '1', '', '2'),
('Petropavlovski D. Alexandru Daniel', 'petropavlovski d alexandru daniel', null, '1', '', '2'),
('Pomponiu V. Ciprian-Constantin', 'pomponiu v ciprian constantin', null, '1', '', '2'),
('Savu M Gabriel', 'savu m gabriel', null, '1', '', '2'),
('Ștoflea D. Nicodim-Andrei', 'stoflea d nicodim andrei', null, '1', '', '2'),
('Tatu E. Cristian-Ionuț', 'tatu e cristian ionut', null, '1', '', '2'),
('Urse P. Roberto-Nicolas', 'urse p roberto nicolas', null, '1', '', '2'),
('Barbu R.T. Alexandru-Robert', 'barbu r t alexandru robert', null, '1', '', '3'),
('Bonev A. Adrian-Emil', 'bonev a adrian emil', null, '1', '', '3'),
('Busuioc O. Laurențiu', 'busuioc o laurentiu', null, '1', '', '3'),
('Carp A Octavian', 'carp a octavian', null, '1', '', '3'),
('Chirilov A. Iulian', 'chirilov a iulian', null, '1', '', '3'),
('Crețu F. Andrei-Ionuț', 'cretu f andrei ionut', null, '1', '', '3'),
('Dima I. Daniel', 'dima i daniel', null, '1', '', '3'),
('Dragnea A. Andrei-Adrian', 'dragnea a andrei adrian', null, '1', '', '3'),
('Feraru G. George-Marian', 'feraru g george marian', null, '1', '', '3'),
('Ivănescu M. Vlăduţ-Mihăiţă', 'ivanescu m vladut mihaita', null, '1', '', '3'),
('Lefter L.M. Antonio-Ioan', 'lefter l m antonio ioan', null, '1', '', '3'),
('Manolache M. Adelin-Ionuț', 'manolache m adelin ionut', null, '1', '', '3'),
('Manole G.A. Ilinca', 'manole g a ilinca', null, '1', '', '3'),
('Marin D Dumitru Adrian', 'marin d dumitru adrian', null, '1', '', '3'),
('Merckx A.L.A Petru-Nicholas-Ioan', 'merckx a l a petru nicholas ioan', null, '1', '', '3'),
('Năstase C. Sorin-Alin', 'nastase c sorin alin', null, '1', '', '3'),
('Pîrvan G. Alexandru-Aurelian', 'pirvan g alexandru aurelian', null, '1', '', '3'),
('Popa I.C. Radu-Andrei', 'popa i c radu andrei', null, '1', '', '3'),
('Radu V.M. Mihai-Alexandru', 'radu v m mihai alexandru', null, '1', '', '3'),
('Sandu N. Elena-Alexandra', 'sandu n elena alexandra', null, '1', '', '3'),
('Stoica L.L. Maria-Lucia', 'stoica l l maria lucia', null, '1', '', '3'),
('Șincă I.C. Antonio-Florin', 'sinca i c antonio florin', null, '1', '', '3'),
('Ștefan C. Cristian-Andrei', 'stefan c cristian andrei', null, '1', '', '3'),
('Tamaș G. Valentin-Raphael', 'tamas g valentin raphael', null, '1', '', '3'),
('Tronaru I. David', 'tronaru i david', null, '1', '', '3'),
('Tudorache I. Andrei-Cristian', 'tudorache i andrei cristian', null, '1', '', '3'),
('Țăvîrlău A. Bety-Cristina-Maria', 'tavirlau a bety cristina maria', null, '1', '', '3'),
('Vasilescu G. Eduard-Andrei', 'vasilescu g eduard andrei', null, '1', '', '3'),
('Verdeș R. Petru- Șerban', 'verdes r petru serban', null, '1', '', '3'),
('Agavriloaie I. Andrei-Iulian', 'agavriloaie i andrei iulian', null, '1', '', '4'),
('Anton G. Elena-Alina', 'anton g elena alina', null, '1', '', '4'),
('Bozempergk T. Grigorios-Alexandros', 'bozempergk t grigorios alexandros', null, '1', '', '4'),
('Cîmpeanu T. Nichita-David', 'cimpeanu t nichita david', null, '1', '', '4'),
('Covataru M.S. Alexandru-Matei', 'covataru m s alexandru matei', null, '1', '', '4'),
('Cristea D. Matei-Alexandru', 'cristea d matei alexandru', null, '1', '', '4'),
('Cuclea S.A. Andrei-Cosmin', 'cuclea s a andrei cosmin', null, '1', '', '4'),
('Dumitrache I. Mihai', 'dumitrache i mihai', null, '1', '', '4'),
('Dumitru D.N. Alexandra-Felicia', 'dumitru d n alexandra felicia', null, '1', '', '4'),
('Frățilă E.G Iustin Alexandru', 'fratila e g iustin alexandru', null, '1', '', '4'),
('Fülöp I. Camelia-Diana-Mihaela', 'fulop i camelia diana mihaela', null, '1', '', '4'),
('Gogoașă M. Augustin', 'gogoasa m augustin', null, '1', '', '4'),
('Jilcu L. Luiza-Ioana', 'jilcu l luiza ioana', null, '1', '', '4'),
('Manea Ș. Mădălin-Gabriel', 'manea s madalin gabriel', null, '1', '', '4'),
('Manolescu B.V.C. Eduard-Ionuț', 'manolescu b v c eduard ionut', null, '1', '', '4'),
('Miron O. Robert', 'miron o robert', null, '1', '', '4'),
('Negraru M. Daniel-Nicolae', 'negraru m daniel nicolae', null, '1', '', '4'),
('Popescu V. Raul-Cristian', 'popescu v raul cristian', null, '1', '', '4'),
('Răducan I.A. Radu-Cristian', 'raducan i a radu cristian', null, '1', '', '4'),
('Ristea I. Ioana-Cătălina', 'ristea i ioana catalina', null, '1', '', '4'),
('Sandu I Vlad-Costin', 'sandu i vlad costin', null, '1', '', '4'),
('Sitaru F. Alexandru-Daniel', 'sitaru f alexandru daniel', null, '1', '', '4'),
('Suceveanu E.I. Eugen-Petru-Ioan', 'suceveanu e i eugen petru ioan', null, '1', '', '4'),
('Ștefan V. Cătălin-Tudor', 'stefan v catalin tudor', null, '1', '', '4'),
('Totolici G.D. Ştefan-Justin', 'totolici g d stefan justin', null, '1', '', '4'),
('Turcu I. Gigel', 'turcu i gigel', null, '1', '', '4'),
('Vancu A. Dariana-Camelia', 'vancu a dariana camelia', null, '1', '', '4'),
('Zaharia M.C. Maria-Miruna', 'zaharia m c maria miruna', null, '1', '', '4'),
('Bărbuță D.G. Eduard-Alexandru', 'barbuta d g eduard alexandru', null, '1', '', '5'),
('Belciug I. Luca', 'belciug i luca', null, '1', '', '5'),
('Botezatu C. Daniel', 'botezatu c daniel', null, '1', '', '5'),
('Calotă D.S. Florentin-Cristian', 'calota d s florentin cristian', null, '1', '', '5'),
('Codrean N. Nelu', 'codrean n nelu', null, '1', '', '5'),
('Costin C. Alexandru', 'costin c alexandru', null, '1', '', '5'),
('Cristea V. Mario-Andrei', 'cristea v mario andrei', null, '1', '', '5'),
('Dinu G. C. Robert Stefan Mihai', 'dinu g c robert stefan mihai', null, '1', '', '5'),
('Drăgan C.A. Marian', 'dragan c a marian', null, '1', '', '5'),
('Drăghici I.A. Răzvan-Ștefan', 'draghici i a razvan stefan', null, '1', '', '5'),
('Homoreanu I Leon Andrei', 'homoreanu i leon andrei', null, '1', '', '5'),
('Huluba C. Alexia-Maria', 'huluba c alexia maria', null, '1', '', '5'),
('Iancu M.S. Dumitru-Gabriel', 'iancu m s dumitru gabriel', null, '1', '', '5'),
('Ionică M.S. Andrei-Roberto', 'ionica m s andrei roberto', null, '1', '', '5'),
('Matache G. Albert-Alexandru', 'matache g albert alexandru', null, '1', '', '5'),
('Paţe F. Alexandru', 'pate f alexandru', null, '1', '', '5'),
('Peneș G. Daiana-Florina', 'penes g daiana florina', null, '1', '', '5'),
('Pop O.A. Andrei-Vlad', 'pop o a andrei vlad', null, '1', '', '5'),
('Popescu I.F. Alexandru-Andrei', 'popescu i f alexandru andrei', null, '1', '', '5'),
('Sima I. Ionuț', 'sima i ionut', null, '1', '', '5'),
('Stinga V. Damian', 'stinga v damian', null, '1', '', '5'),
('Stoica A. Robert-Alexandru', 'stoica a robert alexandru', null, '1', '', '5'),
('Tocaciu V.B. Alexandru', 'tocaciu v b alexandru', null, '1', '', '5'),
('Vasilescu M. Mario-Cristian', 'vasilescu m mario cristian', null, '1', '', '5'),
('Vlad D. Matei-Teodor', 'vlad d matei teodor', null, '1', '', '5'),
('Voicu E. Damian', 'voicu e damian', null, '1', '', '5'),
('Zidaru E. Dima-Theodor', 'zidaru e dima theodor', null, '1', '', '5'),
('Andrei C. Horia', 'andrei c horia', null, '1', '', '6'),
('Avrămescu Ș.B. Andrei-Alexandru', 'avramescu s b andrei alexandru', null, '1', '', '6'),
('Barbu M. Andrei', 'barbu m andrei', null, '1', '', '6'),
('Bucur G. Rareş-Adrian', 'bucur g rares adrian', null, '1', '', '6'),
('Buică N. Iulian', 'buica n iulian', null, '1', '', '6'),
('Burnaz D. Daniel', 'burnaz d daniel', null, '1', '', '6'),
('Cojocaru D.L. Horia-Cristian', 'cojocaru d l horia cristian', null, '1', '', '6'),
('Floarea M. Cristian-Leonardo', 'floarea m cristian leonardo', null, '1', '', '6'),
('Gocea-Ghinea C.N. Octavian-Mihai', 'gocea ghinea c n octavian mihai', null, '1', '', '6'),
('Ichim L.R. Miruna-Anamaria', 'ichim l r miruna anamaria', null, '1', '', '6'),
('Ieșeanu GH. Artur', 'ieseanu gh artur', null, '1', '', '6'),
('Iliescu T. Iustina', 'iliescu t iustina', null, '1', '', '6'),
('Ioniță C. Mihai-Andrei', 'ionita c mihai andrei', null, '1', '', '6'),
('Iovan GH.P. Gheorghe-Dacian', 'iovan gh p gheorghe dacian', null, '1', '', '6'),
('Lecari R. Laurențiu', 'lecari r laurentiu', null, '1', '', '6'),
('Lupu I. Oana-Cristiana', 'lupu i oana cristiana', null, '1', '', '6'),
('Mardare C. Luca-Andrei', 'mardare c luca andrei', null, '1', '', '6'),
('Matei A.C. Petruţ-Cătălin', 'matei a c petrut catalin', null, '1', '', '6'),
('Mocanu F.D. Vlad-Ioan', 'mocanu f d vlad ioan', null, '1', '', '6'),
('Neacșu CE Mihai-Teodor', 'neacsu ce mihai teodor', null, '1', '', '6'),
('Pantofaru V.A. Daniel-Gabriel', 'pantofaru v a daniel gabriel', null, '1', '', '6'),
('Păun Alexandru Andrei', 'paun alexandru andrei', null, '1', '', '6'),
('Radu D. Vasile-Andrei', 'radu d vasile andrei', null, '1', '', '6'),
('Radu G. Mihai-Claudiu', 'radu g mihai claudiu', null, '1', '', '6'),
('Rotaru M.P. Andrei', 'rotaru m p andrei', null, '1', '', '6'),
('Rusu M.C. Alex-Cristian', 'rusu m c alex cristian', null, '1', '', '6'),
('Smadu P. Alexandra', 'smadu p alexandra', null, '1', '', '6'),
('Stoian-Iordache M. Cosmin-Marian', 'stoian iordache m cosmin marian', null, '1', '', '6'),
('Șerbănescu G.P. Matei-George', 'serbanescu g p matei george', null, '1', '', '6'),
('Băican C.M. Fabian-Mihai', 'baican c m fabian mihai', null, '1', '', '7'),
('Bănică G.G. David-Iordănel', 'banica g g david iordanel', null, '1', '', '7'),
('Ciovînă C.C. Roberto-Andrei', 'ciovina c c roberto andrei', null, '1', '', '7'),
('Cîrstea R.S. Valeriu', 'cirstea r s valeriu', null, '1', '', '7'),
('Crăciun-Pavel V. Andrada', 'craciun pavel v andrada', null, '1', '', '7'),
('Diaconescu N.H. Ioan-Silviu-Horia', 'diaconescu n h ioan silviu horia', null, '1', '', '7'),
('Frîncu A.C. Mihail-Cristian', 'frincu a c mihail cristian', null, '1', '', '7'),
('Gogu L.N. Rareș', 'gogu l n rares', null, '1', '', '7'),
('Iancu D. Mario-Alexandro', 'iancu d mario alexandro', null, '1', '', '7'),
('Jivulescu A.I. Ștefan-Constantin', 'jivulescu a i stefan constantin', null, '1', '', '7'),
('Manea C. Sebastian-Andrei', 'manea c sebastian andrei', null, '1', '', '7'),
('Manole I. Mihai-Andrei', 'manole i mihai andrei', null, '1', '', '7'),
('Măgureanu R.V. Andrei', 'magureanu r v andrei', null, '1', '', '7'),
('Miroiu O Onufrie-Alexandru', 'miroiu o onufrie alexandru', null, '1', '', '7'),
('Niculae C. Mircea - Alexandru', 'niculae c mircea alexandru', null, '1', '', '7'),
('Paraschiv I. V. Liviu-Emanuel', 'paraschiv i v liviu emanuel', null, '1', '', '7'),
('Petrișor A. Cosmin-Marius', 'petrisor a cosmin marius', null, '1', '', '7'),
('Popa M.G. Maria', 'popa m g maria', null, '1', '', '7'),
('Sîrbu C.L. Iustin', 'sirbu c l iustin', null, '1', '', '7'),
('Stan F.D. Theodor - Gabriel', 'stan f d theodor gabriel', null, '1', '', '7'),
('Stoian G. Ion', 'stoian g ion', null, '1', '', '7'),
('Tătaru G.V. Cristian Ștefan', 'tataru g v cristian stefan', null, '1', '', '7'),
('Tîrtan I. Cosmin', 'tirtan i cosmin', null, '1', '', '7'),
('Tudor M.I. Alexandru-Marian', 'tudor m i alexandru marian', null, '1', '', '7'),
('Tudor S. Dumitru', 'tudor s dumitru', null, '1', '', '7'),
('Valasciuc Ș. Rareș-Andrei', 'valasciuc s rares andrei', null, '1', '', '7'),
('Alesandrescu O.D. Rareș-Gabriel', 'alesandrescu o d rares gabriel', null, '1', '', '8'),
('Andrei P.D. Sorin-Valentin', 'andrei p d sorin valentin', null, '1', '', '8'),
('Angheluță M. Ciprian-Gabriel', 'angheluta m ciprian gabriel', null, '1', '', '8'),
('Bălărie V. Marius-Vasile', 'balarie v marius vasile', null, '1', '', '8'),
('Călărașu M. Petru-Sergio', 'calarasu m petru sergio', null, '1', '', '8'),
('Chiru C.C. Nicolae-Claudiu', 'chiru c c nicolae claudiu', null, '1', '', '8'),
('Delcea T. George-Valentin', 'delcea t george valentin', null, '1', '', '8'),
('Gherghina B.G. Tudor-Andrei', 'gherghina b g tudor andrei', null, '1', '', '8'),
('Iova C.C. Simona-Georgiana', 'iova c c simona georgiana', null, '1', '', '8'),
('Lăcătuș R.R. Marius-Daniel', 'lacatus r r marius daniel', null, '1', '', '8'),
('Manea D. Andrada-Elena', 'manea d andrada elena', null, '1', '', '8'),
('Manole I.A. Mihai-Eugen', 'manole i a mihai eugen', null, '1', '', '8'),
('Mihai M.F. Alexandru-Valentin', 'mihai m f alexandru valentin', null, '1', '', '8'),
('Mușat-Mare V. Marius-Daniel', 'musat mare v marius daniel', null, '1', '', '8'),
('Năstase GH.D. Ștefan-Robert', 'nastase gh d stefan robert', null, '1', '', '8'),
('Neacșu A. Ana-Maria', 'neacsu a ana maria', null, '1', '', '8'),
('Novac V. Matei', 'novac v matei', null, '1', '', '8'),
('Popa G. Alexandru', 'popa g alexandru', null, '1', '', '8'),
('Rusu D. Romică', 'rusu d romica', null, '1', '', '8'),
('Simion D. Laurențiu-Cristian', 'simion d laurentiu cristian', null, '1', '', '8'),
('Stan F. Alin-Ștefan', 'stan f alin stefan', null, '1', '', '8'),
('Stoicescu M. Alexandru', 'stoicescu m alexandru', null, '1', '', '8'),
('Tanasă S. Marius-Stelu', 'tanasa s marius stelu', null, '1', '', '8'),
('Toma C Mario Andrei', 'toma c mario andrei', null, '1', '', '8'),
('Topor V. Delia-Maria', 'topor v delia maria', null, '1', '', '8'),
('Urlă P. Eduard-Gabriel', 'urla p eduard gabriel', null, '1', '', '8'),
('Uță M.B. Nicolae-Cristian', 'uta m b nicolae cristian', null, '1', '', '8'),
('Voicescu M. Radu', 'voicescu m radu', null, '1', '', '8'),
('Zaharescu C. David-Cristian', 'zaharescu c david cristian', null, '1', '', '8'),
('Badea C. Constantin-Lucian', 'badea c constantin lucian', null, '1', '', '9'),
('Barbu N. Iulian-Daniel', 'barbu n iulian daniel', null, '1', '', '9'),
('Barbu P. Silviu-Petrișor', 'barbu p silviu petrisor', null, '1', '', '9'),
('Bădică M. Mihai-Daniel', 'badica m mihai daniel', null, '1', '', '9'),
('Boldurean P. Petru', 'boldurean p petru', null, '1', '', '9'),
('Borcan I George-Alexandru', 'borcan i george alexandru', null, '1', '', '9'),
('Bucată T. Beniamin-Ruben', 'bucata t beniamin ruben', null, '1', '', '9'),
('Bucur P. Camelia-Mihaela', 'bucur p camelia mihaela', null, '1', '', '9'),
('Dicu L. Damian', 'dicu l damian', null, '1', '', '9'),
('Dincă E.L. Tudor-Nicolae', 'dinca e l tudor nicolae', null, '1', '', '9'),
('Dumitru S. Florin-Valentin', 'dumitru s florin valentin', null, '1', '', '9'),
('Galeriu C. Damian', 'galeriu c damian', null, '1', '', '9'),
('Gavrilescu P. Gabriel', 'gavrilescu p gabriel', null, '1', '', '9'),
('Ionescu A. Smaranda', 'ionescu a smaranda', null, '1', '', '9'),
('Irimia G. Florin Alexandru', 'irimia g florin alexandru', null, '1', '', '9'),
('Lupascu D Ionel', 'lupascu d ionel', null, '1', '', '9'),
('Lupu M. Andrei-Iulian', 'lupu m andrei iulian', null, '1', '', '9'),
('Matei G.F. Florentin', 'matei g f florentin', null, '1', '', '9'),
('Mateiu F. Cristinel', 'mateiu f cristinel', null, '1', '', '9'),
('Muscalu O. David-Andrei', 'muscalu o david andrei', null, '1', '', '9'),
('Panaitiu V. Luca', 'panaitiu v luca', null, '1', '', '9'),
('Pena M.T. Matei', 'pena m t matei', null, '1', '', '9'),
('Perțea V. Ioan', 'pertea v ioan', null, '1', '', '9'),
('Pitulice A.L. Petru-Gabriel', 'pitulice a l petru gabriel', null, '1', '', '9'),
('Popa D. Elisei-Octavian', 'popa d elisei octavian', null, '1', '', '9'),
('Popa P.D. David Iulian', 'popa p d david iulian', null, '1', '', '9'),
('Sava P. Sebastian-Costantino', 'sava p sebastian costantino', null, '1', '', '9'),
('Sevastre D.V Andrei George', 'sevastre d v andrei george', null, '1', '', '9'),
('Stefan D.M. Alexandru-Mihai', 'stefan d m alexandru mihai', null, '1', '', '9'),
('Şerban D. Constantin-Codruţ', 'serban d constantin codrut', null, '1', '', '9'),
('Teiuș P.Ș. Daniel-Andrei', 'teius p s daniel andrei', null, '1', '', '9'),
('Vasilache S. Ștefan-Iulian', 'vasilache s stefan iulian', null, '1', '', '9'),
('Vasile A. Alexandru-Florin', 'vasile a alexandru florin', null, '1', '', '9'),
('Vasile S.L. Andrei Alexandru', 'vasile s l andrei alexandru', null, '1', '', '9'),
('Vasile G. Gean Marco', 'vasile g gean marco', null, '1', '', '9'),
('Zahiu M. Costin- Dobre', 'zahiu m costin dobre', null, '1', '', '9'),
('Albu G. Gheorghe-Mateo', 'albu g gheorghe mateo', null, '1', '', '10'),
('Bărbuceanu I. Constantin', 'barbuceanu i constantin', null, '1', '', '10'),
('Bîșu L. Florian-Antonius', 'bisu l florian antonius', null, '1', '', '10'),
('Caţan V.C. Răzvan-Valentin', 'catan v c razvan valentin', null, '1', '', '10'),
('Ciocîrlan M. Robert-Alexandru-Viorel', 'ciocirlan m robert alexandru viorel', null, '1', '', '10'),
('Ciornei V.M. Robert-Andrei', 'ciornei v m robert andrei', null, '1', '', '10'),
('Cobuz G. Ingrid-Gabriela', 'cobuz g ingrid gabriela', null, '1', '', '10'),
('Cosma N.A. Andrei-Sebastian', 'cosma n a andrei sebastian', null, '1', '', '10'),
('Costache F. Marius-Vlăduț', 'costache f marius vladut', null, '1', '', '10'),
('Crîngea (căs. Maria) N. Georgiana-Denisa', 'cringea cas maria n georgiana denisa', null, '1', '', '10'),
('Dincă P. Alina-Alexandra', 'dinca p alina alexandra', null, '1', '', '10'),
('Dogaru N. Rareș-Nicolae', 'dogaru n rares nicolae', null, '1', '', '10'),
('Dumitru A. Mario-Andrei', 'dumitru a mario andrei', null, '1', '', '10'),
('Enache (căs. Chiru) I.M. Beatrice-Maria', 'enache cas chiru i m beatrice maria', null, '1', '', '10'),
('Enișor E. Paul', 'enisor e paul', null, '1', '', '10'),
('Firu D. Florian-Bogdan', 'firu d florian bogdan', null, '1', '', '10'),
('Gheorghe B. Daniel-Alexandru', 'gheorghe b daniel alexandru', null, '1', '', '10'),
('Gruia C. Florin', 'gruia c florin', null, '1', '', '10'),
('Iacob S.D. Andi-Cristian', 'iacob s d andi cristian', null, '1', '', '10'),
('Ionașcu M. Alexandru-Marian', 'ionascu m alexandru marian', null, '1', '', '10'),
('Ionescu L. Loredana-Maria', 'ionescu l loredana maria', null, '1', '', '10'),
('Ivănuș T. Robert-Dumitru', 'ivanus t robert dumitru', null, '1', '', '10'),
('Manea D. Dumitru-Alexandru', 'manea d dumitru alexandru', null, '1', '', '10'),
('Moldoveanu C. Petrică', 'moldoveanu c petrica', null, '1', '', '10'),
('Murariu I. Andrei-Ionuț', 'murariu i andrei ionut', null, '1', '', '10'),
('Piele C. Dumitru Andrei', 'piele c dumitru andrei', null, '1', '', '10'),
('Popa G Liviu', 'popa g liviu', null, '1', '', '10'),
('Scârtocia I Mihnea-Dumitru', 'scartocia i mihnea dumitru', null, '1', '', '10'),
('Soare V. Andrei-Cosmin', 'soare v andrei cosmin', null, '1', '', '10'),
('Șerban I. Alexandru-George', 'serban i alexandru george', null, '1', '', '10'),
('Trifu V. Ionuț', 'trifu v ionut', null, '1', '', '10'),
('Ursaru A. Ionel-Claudiu', 'ursaru a ionel claudiu', null, '1', '', '10'),
('Vechiu C. Alexandru', 'vechiu c alexandru', null, '1', '', '10'),
('Zaplaic I.G. Radu-Ștefan', 'zaplaic i g radu stefan', null, '1', '', '10'),
('ANDREI C. ROBERT-GABRIEL', 'andrei c robert gabriel', null, '4', '', '11'),
('ANDRONACHE D. IOAN-GABRIEL', 'andronache d ioan gabriel', null, '4', '', '11'),
('AURICĂ M. ANDREI', 'aurica m andrei', null, '4', '', '11'),
('BĂNUȚĂ C. IONUȚ-GABRIEL', 'banuta c ionut gabriel', null, '4', '', '11'),
('BOERU I. IOANA-PARASCHIVA', 'boeru i ioana paraschiva', null, '4', '', '11'),
('BOITOR M. ANDREI-DACIAN', 'boitor m andrei dacian', null, '4', '', '11'),
('BORCEA C. GEORGE IOAN', 'borcea c george ioan', null, '4', '', '11'),
('BOȘCU C. PETRICĂ-DĂNUȚ', 'boscu c petrica danut', null, '4', '', '11'),
('BUNEA M. DRAGOȘ-FLORIN', 'bunea m dragos florin', null, '4', '', '11'),
('BUNESCU V. ANDREI', 'bunescu v andrei', null, '4', '', '11'),
('BURCIU F. LILIANA', 'burciu f liliana', null, '4', '', '11'),
('DOGARU V. ROBERT-SEBASTIAN', 'dogaru v robert sebastian', null, '4', '', '11'),
('DRAGNEA S. ALEXANDRU-GABRIEL', 'dragnea s alexandru gabriel', null, '4', '', '11'),
('DRUMEA M. MIHAIL RĂZVAN', 'drumea m mihail razvan', null, '4', '', '11'),
('DUDU S. STELIAN ALIN', 'dudu s stelian alin', null, '4', '', '11'),
('DULUGEAC V. MARIA-POLIXENIA', 'dulugeac v maria polixenia', null, '4', '', '11'),
('ENE V. RADU-ANDREI', 'ene v radu andrei', null, '4', '', '11'),
('EPURE C.D. ANDREI-FLORIN', 'epure c d andrei florin', null, '4', '', '11'),
('GHEORGHE D.L. ALEXANDRU', 'gheorghe d l alexandru', null, '4', '', '11'),
('GIGER H.P. RUBEN', 'giger h p ruben', null, '4', '', '11'),
('GIURESCU E. MATEI-PARASCHIV', 'giurescu e matei paraschiv', null, '4', '', '11'),
('GRECU I. VICTOR - FLORIN', 'grecu i victor florin', null, '4', '', '11'),
('HARCAN I. ANDREI VLĂDUȚ', 'harcan i andrei vladut', null, '4', '', '11'),
('HURU V. ALEXANDRU-COSMIN', 'huru v alexandru cosmin', null, '4', '', '11'),
('IACOB M. VLAD-ȘTEFAN', 'iacob m vlad stefan', null, '4', '', '11'),
('ION G.A. MARIAN-ALIN', 'ion g a marian alin', null, '4', '', '11'),
('IONESCU N. VICTOR ANDREI', 'ionescu n victor andrei', null, '4', '', '11'),
('JARCĂ D. DANIEL-CONSTANTIN', 'jarca d daniel constantin', null, '4', '', '11'),
('JUJAN D. FLAVIUS DANIEL', 'jujan d flavius daniel', null, '4', '', '11'),
('MANEA M.C. THEODOR-IOAN', 'manea m c theodor ioan', null, '4', '', '11'),
('MĂNESCU E. DAVID-VALENTIN', 'manescu e david valentin', null, '4', '', '11'),
('MARANCEA F. OANA-LOREDANA', 'marancea f oana loredana', null, '4', '', '11'),
('MATEI A. MARIAN-STELIAN', 'matei a marian stelian', null, '4', '', '11'),
('MATEI C. MIHAI BOGDAN', 'matei c mihai bogdan', null, '4', '', '11'),
('MIHAI G. ROBERT CRISTIAN', 'mihai g robert cristian', null, '4', '', '11'),
('MIHAI S. ALIN - ANDREI', 'mihai s alin andrei', null, '4', '', '11'),
('MINOIU A. TEODOR', 'minoiu a teodor', null, '4', '', '11'),
('MIRESCU V. ANDREI-PETRE', 'mirescu v andrei petre', null, '4', '', '11'),
('NAE E. ANAMARIA-ANDREEA', 'nae e anamaria andreea', null, '4', '', '11'),
('NEAGU M. MARIAN-GABRIEL', 'neagu m marian gabriel', null, '4', '', '11'),
('NEGREA B.G. VLĂDUȚ-GABRIEL', 'negrea b g vladut gabriel', null, '4', '', '11'),
('NIȚĂ B.I. CĂTĂLIN-MARIAN', 'nita b i catalin marian', null, '4', '', '11'),
('NIȚU L. ALEXANDRU', 'nitu l alexandru', null, '4', '', '11'),
('OLARI C. ANDREI', 'olari c andrei', null, '4', '', '11'),
('OLARU M. BOGDAN-DANIEL', 'olaru m bogdan daniel', null, '4', '', '11'),
('OLTEANU D. MIHAI', 'olteanu d mihai', null, '4', '', '11'),
('ONIȘOARĂ N. CEZAR', 'onisoara n cezar', null, '4', '', '11'),
('PAULEȚU G. CONSTANTIN-RĂZVAN', 'pauletu g constantin razvan', null, '4', '', '11'),
('PAVEL D. CEZAR', 'pavel d cezar', null, '4', '', '11'),
('PESCARU S.P. RĂZVAN ANDREI', 'pescaru s p razvan andrei', null, '4', '', '11'),
('PÎRCĂLĂBELU V. GHEORGHE', 'pircalabelu v gheorghe', null, '4', '', '11'),
('POPA A.B. ADINA MARILENA', 'popa a b adina marilena', null, '4', '', '11'),
('POPESCU GH. IULIAN-FLORIN', 'popescu gh iulian florin', null, '4', '', '11'),
('POPESCU M. SANDU OCTAVIAN', 'popescu m sandu octavian', null, '4', '', '11'),
('POPESCU M.C. ANDREEA-MARIA', 'popescu m c andreea maria', null, '4', '', '11'),
('PREDA C. ALEXANDRU', 'preda c alexandru', null, '4', '', '11'),
('PRUTEANU P. MARIUS', 'pruteanu p marius', null, '4', '', '11'),
('RADU M. SILVIU MIHAI', 'radu m silviu mihai', null, '4', '', '11'),
('ROȘCA D.E. TUDOR-DUMITRU', 'rosca d e tudor dumitru', null, '4', '', '11'),
('ROȘU G. DANIEL-GEORGE', 'rosu g daniel george', null, '4', '', '11'),
('ROTARU C. LARISA - MIHAELA', 'rotaru c larisa mihaela', null, '4', '', '11'),
('RUSEANU I. GHEORGHE-NICOLAE', 'ruseanu i gheorghe nicolae', null, '4', '', '11'),
('SIMILIAC T. IOANA - TEODORA', 'similiac t ioana teodora', null, '4', '', '11'),
('SÎRBU C. DANIEL-ANDREI', 'sirbu c daniel andrei', null, '4', '', '11'),
('SOTIR S.D. ANTONIO GABRIEL', 'sotir s d antonio gabriel', null, '4', '', '11'),
('STANCIU N. MANUELA-NICOLETA', 'stanciu n manuela nicoleta', null, '4', '', '11'),
('TĂNASĂ-ANEA C. RĂZVAN-ANDREI', 'tanasa anea c razvan andrei', null, '4', '', '11'),
('TEODORESCU C.I. ALEXANDRU', 'teodorescu c i alexandru', null, '4', '', '11'),
('TRUNCHIU C. NICOLAE COSMIN', 'trunchiu c nicolae cosmin', null, '4', '', '11'),
('TUDOR G. EDUARD-ANDREI', 'tudor g eduard andrei', null, '4', '', '11'),
('TUDORAN B.P. CIPRIAN-VLĂDUȚ', 'tudoran b p ciprian vladut', null, '4', '', '11'),
('TURCU C. ȘTEFAN', 'turcu c stefan', null, '4', '', '11'),
('UNGUREANU P VICTOR-IULIAN', 'ungureanu p victor iulian', null, '4', '', '11'),
('URSEI I. EMILIAN', 'ursei i emilian', null, '4', '', '11'),
('UȚĂ FL. IONUȚ ALEXANDRU', 'uta fl ionut alexandru', null, '4', '', '11'),
('VASILE V. ALEXANDRU-IONUȚ', 'vasile v alexandru ionut', null, '4', '', '11'),
('VÎLCEA M. MARIUS FLORIAN', 'vilcea m marius florian', null, '4', '', '11'),
('VIOREL C. CRISTIAN-ALEXANDRU', 'viorel c cristian alexandru', null, '4', '', '11'),
('VÎRJE D. DRAGOȘ-MARIUS', 'virje d dragos marius', null, '4', '', '11'),
('VIȘAN N. ANGHEL CRISTIAN', 'visan n anghel cristian', null, '4', '', '11'),
('VOICU V. SEBASTIAN-ȘTEFAN', 'voicu v sebastian stefan', null, '4', '', '11'),
('VOINEA I. VLAD ANDREI', 'voinea i vlad andrei', null, '4', '', '11'),
('ZAMFIR M. ALEXANDRU-CRISTIAN', 'zamfir m alexandru cristian', null, '4', '', '11'),
('ZOTESCU B.N. BOGDAN-ȘTEFAN', 'zotescu b n bogdan stefan', null, '4', '', '11')
on conflict do nothing;
